#!/usr/bin/env python
#

import argparse

from src.ast import AST
from src.midicomp_exporter import MidicompExporter
from src.parser_rules import SemanticException

parser = argparse.ArgumentParser(description='Musileng - Compositor Musical.')

parser.add_argument('input_file')
parser.add_argument('output_file')
parser.add_argument('--ast', '-a', help='Dump AST into a .dot file', nargs=1)

args = parser.parse_args()
if args.ast != None: args.ast = args.ast[0]

# End of argument parsing.

# Main program
try:
  ast = AST(args.input_file)
  MidicompExporter(ast).export(args.output_file)

  if args.ast: ast.dump_ast(args.ast)

except SemanticException as exception:
  print "Semantic error: " + str(exception)
except Exception as exception:
  print "Syntax error " + str(exception)
else:
  print "Syntax is valid."
