#!/usr/bin/env python
#

import argparse
from ast import AST
from midicomp_exporter import MidicompExporter

parser = argparse.ArgumentParser(description='Musileng - Compositor Musical.')

parser.add_argument('input_file')
parser.add_argument('output_file')
parser.add_argument('--ast', '-a', help='Dump AST into a .dot file', nargs=1)

args = parser.parse_args()
if args.ast != None: args.ast = args.ast[0]

# End of argument parsing.

# Main program
try:
  ast = AST(args.input_file)
  MidicompExporter(ast).export(args.output_file)

  if args.ast: ast.dump_ast(args.ast)

except Exception as exception:
  print "Syntax error " + str(exception)
except parser_rules.SemanticException as exception:
  print "Semantic error: " + str(exception)
else:
  print "Syntax is valid."
