
# /Users/emancu/tl/tp2/src/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '941D047E6C0AE9C772F836F2FA32677C'
    
_lr_action_items = {'CONST':([5,8,18,25,],[-5,10,-3,-4,]),'TEMPO':([0,],[1,]),'NUMBER':([4,6,14,16,19,32,55,],[7,9,18,21,21,21,21,]),'REPEAT':([26,27,44,57,],[28,28,-13,-14,]),'DURATION':([45,63,],[50,50,]),'DIV':([9,],[14,]),'VOICE':([5,8,13,18,25,33,],[-5,12,12,-3,-4,-10,]),'RPAREN':([20,21,22,35,49,50,51,65,],[-7,-6,24,41,-24,-25,56,66,]),'SEMICOLON':([20,21,23,56,66,],[-7,-6,25,61,67,]),'LCURLYBRACKET':([24,30,41,53,],[26,34,47,58,]),'RCURLYBRACKET':([26,27,29,31,34,37,38,40,43,44,46,47,52,54,57,58,59,61,62,64,67,],[-12,-12,33,-11,-20,-20,44,-20,-19,-13,-21,-17,57,-17,-14,-20,-15,-23,64,-16,-22,]),'COMMA':([20,21,48,60,],[-7,-6,55,63,]),'COMPASS':([26,27,44,47,54,57,64,],[30,30,-13,53,53,-14,-16,]),'$end':([3,5,8,11,13,17,18,25,33,],[0,-5,-9,-1,-9,-8,-3,-4,-10,]),'NOTE_ID':([42,],[48,]),'FIGURE':([1,45,63,],[4,49,49,]),'EQUAL':([15,],[19,]),'LPAREN':([12,28,36,39,],[16,32,42,45,]),'SILENCE':([34,37,40,58,61,67,],[39,39,39,39,-23,-22,]),'NAME':([10,16,19,32,55,],[15,20,20,20,20,]),'NOTE':([34,37,40,58,61,67,],[36,36,36,36,-23,-22,]),'COMPASS_V':([2,7,],[6,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'te':([0,],[2,]),'co':([2,],[5,]),'vars':([5,],[8,]),'repeat_content':([47,54,],[52,59,]),'cons_val':([16,19,32,55,],[22,23,35,60,]),'voices':([8,13,],[11,17,]),'note':([34,37,40,58,],[37,37,37,37,]),'compass_content':([34,37,40,58,],[38,43,46,62,]),'compass_or_repeat':([26,27,],[27,27,]),'voice_content':([26,27,],[29,31,]),'compass':([47,54,],[54,54,]),'figure_duration':([45,63,],[51,65,]),'voice':([8,13,],[13,13,]),'expression':([0,],[3,]),'silence':([34,37,40,58,],[40,40,40,40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> te co vars voices','expression',4,'p_expression_initial','parser_rules.py',14),
  ('te -> TEMPO FIGURE NUMBER','te',3,'p_expression_tempo','parser_rules.py',18),
  ('co -> COMPASS_V NUMBER DIV NUMBER','co',4,'p_expression_compass_v','parser_rules.py',22),
  ('vars -> vars CONST NAME EQUAL cons_val SEMICOLON','vars',6,'p_vars','parser_rules.py',27),
  ('vars -> <empty>','vars',0,'p_vars_empty','parser_rules.py',44),
  ('cons_val -> NUMBER','cons_val',1,'p_cons_val_number','parser_rules.py',47),
  ('cons_val -> NAME','cons_val',1,'p_cons_val_name','parser_rules.py',51),
  ('voices -> voice voices','voices',2,'p_expression_voices','parser_rules.py',55),
  ('voices -> <empty>','voices',0,'p_expression_voices_empty','parser_rules.py',60),
  ('voice -> VOICE LPAREN cons_val RPAREN LCURLYBRACKET voice_content RCURLYBRACKET','voice',7,'p_expression_voice','parser_rules.py',63),
  ('voice_content -> compass_or_repeat voice_content','voice_content',2,'p_expression_voice_content','parser_rules.py',71),
  ('voice_content -> <empty>','voice_content',0,'p_expression_voice_content_empty','parser_rules.py',78),
  ('compass_or_repeat -> COMPASS LCURLYBRACKET compass_content RCURLYBRACKET','compass_or_repeat',4,'p_expression_compass','parser_rules.py',81),
  ('compass_or_repeat -> REPEAT LPAREN cons_val RPAREN LCURLYBRACKET repeat_content RCURLYBRACKET','compass_or_repeat',7,'p_expression_compass_repeat','parser_rules.py',85),
  ('repeat_content -> compass repeat_content','repeat_content',2,'p_expression_repeat_content','parser_rules.py',89),
  ('compass -> COMPASS LCURLYBRACKET compass_content RCURLYBRACKET','compass',4,'p_expression_compass_only','parser_rules.py',93),
  ('repeat_content -> <empty>','repeat_content',0,'p_expression_repeat_content_empty','parser_rules.py',97),
  ('compass_or_repeat -> <empty>','compass_or_repeat',0,'p_expression_compass_empty','parser_rules.py',100),
  ('compass_content -> note compass_content','compass_content',2,'p_expression_voice_compass_content_note','parser_rules.py',103),
  ('compass_content -> <empty>','compass_content',0,'p_expression_compass_content_empty','parser_rules.py',112),
  ('compass_content -> silence compass_content','compass_content',2,'p_expression_voice_compass_content_silence','parser_rules.py',115),
  ('note -> NOTE LPAREN NOTE_ID COMMA cons_val COMMA figure_duration RPAREN SEMICOLON','note',9,'p_expression_note','parser_rules.py',124),
  ('silence -> SILENCE LPAREN figure_duration RPAREN SEMICOLON','silence',5,'p_expression_silence','parser_rules.py',128),
  ('figure_duration -> FIGURE','figure_duration',1,'p_expression_figure','parser_rules.py',132),
  ('figure_duration -> DURATION','figure_duration',1,'p_expression_duration','parser_rules.py',136),
]
